[project]
name = "firecrawl-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "firecrawl-py>=4.6.0",
    "requests>=2.32.5",
]
